package com.example.sprink.api;

import com.example.sprink.NotaRepository;
import com.example.sprink.domain.Nota;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/note") // This means URL's start with /demo (after Application path)
 public class NotaController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private NotaRepository notaRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewNota(@RequestParam String title
            , @RequestParam String content, @RequestParam String user, @RequestParam String color) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Nota n = new Nota();
       n.setContent(content);
       n.setIdUser(user);
       n.setTitle(title);
       n.setColor(color);
        notaRepository.save(n);
        return "Saved";
    }


    @GetMapping(path = "/all")
    public @ResponseBody
    List<Nota> getAllNote() {
        // This returns a JSON or XML with the users
        return notaRepository.findAll();

    }
    @GetMapping("all/{id}")

    public @ResponseBody
    Optional<Nota> getNotaById(@PathVariable("id") String id){
        return notaRepository.findById(Integer.parseInt(id));}



    @DeleteMapping // Map ONLY POST Requests
    public @ResponseBody
    String delNewNota(@RequestParam String id) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        //long nt=Long.valueOf(id);
       // Optional<Nota> nota= notaRepository.findById(Long.valueOf(id));
        notaRepository.deleteById(Integer.parseInt(id));
        return "cancellato";
    }




}
