package com.example.sprink.api;

import com.example.sprink.NotaRepository;
import com.example.sprink.domain.Nota;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
@Controller // This means that this class is a Controller
@RequestMapping(path = "/note") // This means URL's start with /demo (after Application path)
 public class NotaController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private NotaRepository notaRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewNota(@RequestParam String title
            , @RequestParam String content, @RequestParam String user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Nota n = new Nota();
       n.setContent(content);
       n.setIdUser(user);
       n.setTitle(title);
        notaRepository.save(n);
        return "Saved";
    }


    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Nota> getAllNote() {
        // This returns a JSON or XML with the users
        return notaRepository.findAll();

    }}
